# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: csv_maker.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x63sv_maker.proto\x12\x0f\x43svMakerService\"=\n\x0e\x45xtractRequest\x12+\n\tdata_rows\x18\x01 \x03(\x0b\x32\x18.CsvMakerService.DataRow\"\x16\n\x07\x44\x61taRow\x12\x0b\n\x03row\x18\x01 \x03(\t\"!\n\x0eStreamResponse\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\x32^\n\x08\x43svMaker\x12R\n\x08\x42uildCsv\x12\x1f.CsvMakerService.ExtractRequest\x1a\x1f.CsvMakerService.StreamResponse\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'csv_maker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EXTRACTREQUEST']._serialized_start=36
  _globals['_EXTRACTREQUEST']._serialized_end=97
  _globals['_DATAROW']._serialized_start=99
  _globals['_DATAROW']._serialized_end=121
  _globals['_STREAMRESPONSE']._serialized_start=123
  _globals['_STREAMRESPONSE']._serialized_end=156
  _globals['_CSVMAKER']._serialized_start=158
  _globals['_CSVMAKER']._serialized_end=252
# @@protoc_insertion_point(module_scope)
